version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.13-apache-node-browsers-legacy
    working_directory: ~/tea-messenger-api
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: php .circleci/php/php_syntax_checker.php
      - run: apt update -y

      # Build Database
      - run: apt install -y mysql-server
      - run: service mysql start
      - run: mysql -u root -e "CREATE DATABASE teamesenger;"
      - run: mysql -u root -e "GRANT ALL PRIVILEGES ON teamesenger.* TO 'teamesenger'@'localhost' IDENTIFIED BY '123qweASDzxc';"
      - run: mysql -u root teamesenger < database.sql

      # Build Application
      - run: cp config/app.php.example config/app.php
      - run: cp config/database.php.example config/database.php
      - run: composer install -n --prefer-dist -vvv

      # Save Cache
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: sh -c "php server.php > logs/php_server.log 2>&1 &"
      - run: phpunit