version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.13-apache-node-browsers-legacy
    working_directory: ~/tea-messenger-api
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: php .circleci/php/php_syntax_checker.php
      - run: sudo apt update -y

      # Build Database
      - run: sudo apt install -y mysql-server
      - run: sudo service mysql start
      - run: sudo mysql -u root -e "CREATE DATABASE teamessenger;"
      - run: sudo mysql -u root -e "GRANT ALL PRIVILEGES ON teamessenger.* TO 'teamessenger'@'localhost' IDENTIFIED BY '123qweASDzxc';"
      - run: sudo mysql -u root teamessenger < database.sql

      # Build Application
      - run: cp config/app.php.example config/app.php
      - run: cp config/database.php.example config/database.php
      - run: cp config/base_api_url.php.example config/base_api_url.php
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-enable pdo_mysql
      - run: composer install -n --prefer-dist -vvv

      # Save Cache
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: sh -c "php server.php > logs/php_server.log 2>&1 &" && php phpunit -vvv